### PR TITLE
Remove error email and expose all episodes in RSS.

### PR DESCRIPTION
**Pull request by mbrandonw**
Removing that `Private Rss Feed Error` email cause I think we know what is going on there. Also I'm now exposing all episodes in the private RSS feed. Seems maybe not worth doing what we are doing to combat fraudulent activity. Thoughts?

### CODE REVIEW

**Comment by stephencelis** [comment]
Can we do a month-size window instead?

**Comment by mbrandonw** [comment]
> Can we do a month-size window instead?

coo yeah let's try that.

**Comment by mbrandonw** [comment]
> Looks good but I think still needs a `.prefix(4)` or somethin.

why's that? I'm only exposing episodes published in the last 30 days.

**Comment by stephencelis** [comment]
Ah my brain skipped right past that. Looks good!

**Pull request merged**
